<?php

/**
 * AbsenceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AbsenceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AbsenceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Absence');
    }
}