<?php

/**
 * AdministrateurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdministrateurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdministrateurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Administrateur');
    }
}