<?php

/**
 * CoursTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CoursTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CoursTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cours');
    }
}