<?php

/**
 * EnseignantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EnseignantTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EnseignantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Enseignant');
    }
}