<?php

/**
 * EnseignantMatiereTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EnseignantMatiereTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EnseignantMatiereTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EnseignantMatiere');
    }
}