<?php

/**
 * EtudiantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EtudiantTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EtudiantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Etudiant');
    }
}