<?php

/**
 * EtudiantPromotionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EtudiantPromotionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EtudiantPromotionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EtudiantPromotion');
    }
}