<?php

/**
 * ExerciceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExerciceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExerciceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Exercice');
    }
}