<?php

/**
 * MatiereTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MatiereTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MatiereTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Matiere');
    }
}